name: CI/CD for Node.js App

# Trigger workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    # Specify the environment
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests
    - name: Run tests
      run: npm test

    # Step 5: Build Docker image
    - name: Build Docker image
      run: docker build -t sabursaigani/hw1_api:latest .

    # Step 6: Push Docker image to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push sabursaigani/hw1_api:latest

  deploy:
    # Ensure this job runs after the build job
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Deploy the app (e.g., using SSH to an EC2 server)
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/hw1_api
          git pull origin main
          docker pull sabursaigani/hw1_api:latest
          docker stop hw1_api || true
          docker rm hw1_api || true
          docker run -d -p 3000:3000 --name hw1_api sabursaigani/hw1_api:latest
