name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest  # This can be any runner you prefer, e.g., `ubuntu-latest`
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # This checks out the code from your repository

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3  # This action is used to set up the SSH key for authentication
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # The private SSH key secret that GitHub Actions uses

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.4  # This is the action that runs SSH commands on your EC2 instance
      with:
        host: ${{ secrets.EC2_HOST }}  # The IP address or DNS of your EC2 instance (stored as a secret)
        username: ec2-user  # Your EC2 instance's username, typically 'ec2-user' for Amazon Linux or 'ubuntu' for Ubuntu instances
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # The SSH private key secret to authenticate
        port: 22  # The SSH port (22 by default)
        script: |
          echo "Starting SSH connection"
          cd /home/your-user/hw1_api
          git pull origin main
          docker pull sabursaigani/hw1_api:latest
          docker stop hw1_api || true
          docker rm hw1_api || true
          docker run -d -p 3000:3000 --name hw1_api sabursaigani/hw1_api:latest
